language: objective-c
script:
- xcodebuild test -project JsonPatchDemo/JsonPatchDemo.xcodeproj -scheme JsonPatchDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'name=iPhone X,OS=11.1'
- osascript -e 'tell app "Simulator" to quit'
- xcodebuild test -project JsonPatchDemo/JsonPatchDemo.xcodeproj -scheme JsonPatchDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'name=iPhone 5s,OS=8.1'

